ptcrealitylab/vuforia-spatial-toolbox-userinterface

src/app/targetDownloader.js, src/device/onLoad.js, src/gui/settings/index.js, src/network/index.js
Previous fixes were stop-gap, didn't actually keep track of which files had been previously downloaded/cached and which ones hadn't was leading to edge case bugs. This tries to fix it properly.
=> More thoroughly keep track of caching in target downloader 

src/gui/ar/draw.js, src/gui/ar/grouping.js
I broke the way tools fade away when you move farther away from them when I refactored this variable. This fixes it.
=> fix reference to distance getter function that was refactored

src/app/callbacks.js, src/app/targetDownloader.js, src/gui/ar/index.js
This fixes half of the problem.
Intercepts matrices detected by Vuforia before they get passed to visibleObjects, and multiplies those that use the instant image target API by a scale factor. Ideally instead of scaling the size by 3x we would adjust the position so that it's just 3x closer to the camera, but this is the wrong place in the pipeline to do it and I'm not sure where the right place is.
Separately adjusts the visibility distance for instant image targets to be 3x as far because they are treated as being 3x as far away. 
Thoughts?
=> adds temporary fix for instant image targets

.eslintrc.js, src/app/targetDownloader.js, src/device/onLoad.js, src/device/videoRecording.js, src/gui/ar/draw.js, src/gui/ar/grouping.js, src/gui/crafting/blockMenu.js, src/gui/crafting/eventHelper.js, src/gui/crafting/index.js, src/gui/memory/index.js, src/gui/pocket.js, src/network/availableFrames.js, src/network/index.js, src/network/realtime.js, src/states.js, src/worldObjects.js
This is a critical update to allow servers with different ports.
It is required to improve stability on iOS devices.
Why?
Its possible that multiple server run in the background on an ios device. 
Using common ports like 80, 8080 or 8888 can increase the potential for application crashes.
Therefore the server is moved to a new port. That needs to be reflected in:
ios app
user interface
server
=> Allow server from different ports

css/index.css, src/gui/ar/anchors.js, src/gui/ar/index.js, src/gui/screenExtension.js, src/gui/spatial/index.js, src/network/availableFrames.js, src/worldObjects.js
Here are the updates for anchors which can be merged back into your code.
- The object name textfield on the anchor scales down so that the name always fits in the box.
- I updated how we calculate the closest object/frame/node to use the `modelViewMatrices` instead of the `visibleObjects` matrices because for regular objects these are equal, but for anchor objects the `modelViewMatrices` are more correct.
- You can now attach tools from the pocket to the closest anchor, and when you move the anchor around the tools move with it!
=> Ben anchor updates

src/envelopeManager.js
Hard to track down, easy to fix. I had passed in the incorrect frameKey argument to realityEditor.device.deleteFrame, causing envelopes to be deleted multiple times if they had any frames inside them.
This triggered a domino effect that left their elements stuck on the screen after deletion.
Fixes issue #86
=> fixes bug when deleting envelope with frames inside of it

src/gui/spatial/index.js, src/index.js, src/states.js
Didn't test / notice that initializing a p5 canvas somehow sets display:none on all(?) other canvases when it finishes loading, so the links were being hidden. quick fix by setting back to visible after a timeout. (first commit)
also, added code reformat for spatial/index.js (second and third commits)
=> Hotfix hidden canvas

index.html, src/device/distanceScaling.js, src/device/environment.js, src/device/index.js, src/device/onLoad.js, src/device/utilities.js, src/gui/ar/draw.js, src/gui/ar/index.js, src/gui/ar/lines.js, src/gui/ar/utilities.js, src/gui/crafting/blockMenu.js, src/gui/pocket.js, src/index.js, src/network/realtime.js
Can I get feedback on this design change?
**Motivation**: the iPad rendering was broken because it mistakenly evaluated isDesktop to true because of changes to window.navigation.userAgent. Rather than simply change this to a more accurate check, I thought it would be better if some variables/features were explicitly enabled by the add-ons that require them (e.g. internalResearch-addon), and default to normal app behavior if the add-on is not present.
**Method**: I split up the isDesktop variable into a set of variables based on what it was being used for, and added setters/getters for those capabilities to src/device/environment.js. This means that new add-ons can selectively trigger certain behavior in the core app by toggling these environment vars. Essentially decouples the add-on from …
=> "environment" refactor

src/app/callbacks.js
It appears that the ground plane bug wasn't actually that it was rotated 90 degrees, but actually that the ground plane was snapping to the orientation/position that the phone was held at when it opened. This is because I forgot to exclude the WORLD_local from the world origins that the ground plane snaps to.
I tried on my own object and it seemed to work. Can someone else verify that this works?
=> fixes groundplane orientation by not snapping to WORLD_local

src/gui/ar/anchors.js, src/worldObjects.js
Fixes the bug where the pocket could be empty if the server didn't initialize the local world object in time, by not giving up on loading the local world after several attempts. also includes better error handling if local world object isn't loaded yet.
Tested this on an app where the local edge-server delayed initializing its local world object by 10 seconds, e.g:
```
if (globalVariables.worldObject) {
setTimeout(function() {
loadWorldObject();
}, 10000);
}
```
@hobinjk-ptc can you check that this fixes it for you?
=> adjusts process to load local world object so that it keeps trying until successful

src/constructors.js, src/gui/crafting/index.js, src/index.js
Draws links from edge of screen to the input/output blocks in those columns within the crafting board. This should help with the mental leap of tying together what's happening in AR with what's happening in the grid. Also helps with debugging, for example if you connected the wrong color on the outside you'd notice when programming it.
=> visualizes links to/from logic node's different colors

src/network/index.js
fixes bug where type-specific node properties (such as invisibility and default publicData fields) didn't propagate to app when initNode is called. if server sends back the initialized node data as a response to the post request, the app now uses that to update the local placeholder node that it generates.
=> loads node properties correctly from server when initNode is called from new tool

src/gui/ar/draw.js, src/network/index.js
Renders the node like it's a sticky fullscreen frame (but can still be repositioned, scaled, and linked)
How to use in a tool:
```
realityInterface.initNode('left', 'node', -100, 0);
realityInterface.initNode('right', 'node', 100, 0);
realityInterface.initNode('top', 'node', 0, -100);
realityInterface.initNode('bottom', 'node', 0, 100);
realityInterface.stickNodeToScreen('left');
realityInterface.stickNodeToScreen('right');
realityInterface.stickNodeToScreen('top');
realityInterface.stickNodeToScreen('bottom');
```
=> adds API for stickNodeToScreen(nodeName) 

src/app/index.js, src/gui/ar/areaTargetScanner.js
When toggled on in the develop menu, stop the area target scan when app memory exceeds a specified percentage of total device memory (default = 33%). Also responds to native `UIApplicationDidReceiveMemoryWarningNotification` but that usually happens too late in my tested environment (around 50%) to upload without crashing. 
Native APIs already exist, no other PRs needed for this change.
=> Use memory warning API to stop area target scan before crash

index.html, src/device/onLoad.js, src/gui/ar/draw.js, src/gui/ar/groundPlaneRenderer.js, src/gui/ar/groundplaneAnchors.js, src/gui/glRenderer.js, src/gui/pocket.js, src/gui/threejsScene.js, src/index.js, src/network/index.js
Toggling on this mode (in the settings menu or with "P" key on remote operator) shows threejs icons anchored to groundplane underneath each tool. Dragging the anchors moves the tools along that plane. Also adds API for tools to subscribe directly to the anchor modelView.
NOTE: this currently only works on remote operator because it's reliant on raycasting against the area target mesh. I will update soon to work in AR with the ground plane.
=> Tool groundplane anchor repositioning mode

css/index.css, src/gui/ar/groundPlaneAnchors.js, src/gui/threejsScene.js
Paired with the latest changes on the remote operator's depth-representation branch this tries to do away with the touchEventCatcher pattern
It is a bit flaky and prone to race conditions with how convoluted the startup process is. I'm trying to improve this but if it's not working just click into and out of logic mode and the settings menu
=> Better touch event handling

src/gui/threejsScene.js
This uses the approach from the vertex shader in the fragment shader where it looks for parts of the three.js shader that probably won't change and puts the new code next to them. Previous approach was to copy-paste the entire three.js shader and add stuff to it willy-nilly which isn't as scalable. Both approaches can randomly explode when updating three.js but the replacement has the advantage of being much simpler.
=> Simplify loading effect shaders; Rewrite fragment shader as find-and-replace

src/app/targetDownloader.js, src/device/environment.js, src/device/index.js, src/gui/threejsScene.js
If there is an occlusion mesh added to the scene (on AR devices), pointerevents posted into iframes will contain an additional `projectedZ` property calculated by raycasting against the occlusion mesh. If there isn't an occlusion mesh, but there is an area target gltf (on remote operator), raycasts against that instead.
**Question for reviewers**: are we ok accepting a performance cost on AR devices of loading the area target occlusion gltf into the three.js scene for this feature? I expect we'll make more and more use of it in the future, if we also implement snapping tools' positions to surfaces, etc.
=> ProjectedZ PointerEvents API

src/device/index.js, src/gui/threejsScene.js
I realized that I didn't include this in the previous version, but you might want easy access to the `rayDirection` within the `worldIntersectPoint` provided to tools
=> adds rayDirection to worldIntersectPoint

css/index.css, src/app/callbacks.js, src/device/environment.js, src/gui/ar/areaTargetScanner.js, src/gui/ar/draw.js, src/gui/pocket.js
necessary for the pop-up-onboarding-addon to adjust the UI and trigger a custom area target scanning workflow
Includes:
- `suppressObjectDetections`: so that we have the option to ignore UDP heartbeats while app is in main menu
- `suppressObjectRendering`: so that we can ignore all rendering and hide all AR elements when we open various menus, or during the scanning process
- `overrideAreaTargetScanningUI`: so that we can customize the buttons/text that appears while scanning
- `automaticallyPromptForAreaTargetCapture`: can be disabled to ignore the default scanning flow
- callbacks for areaTargetScanner.js (`onStartScanning`, `onCaptureStatus`, `onStopScanning`, `onCaptureSuccessOrError`), and public method to `programmaticallyStartScan`: so that we can provide a customized UI/UX for …
=> adds environment variables and callbacks for customized area target scanning

src/device/environment.js, src/envelopeManager.js
Allows remote operator menubar to adjust the top alignment. Could also be used in future by portrait mode app to avoid the screen notch at the top.
=> add screenTopOffset to move envelope X button lower

src/device/index.js, src/device/onLoad.js
Mass-blocks all middle mouse button and right mouse button clicks using a helper function. Adds a button property to the frame's pointer event as well (even though it should only be button: 0 in theory). Adds a notification (shamelessly stolen from the scanning api) about when the network is offline
=> Ignore camera control clicks; Add offline check

thirdPartyCode/three-mesh-bvh.module.js
The previous path went up by one too many levels which works locally but breaks on toolboxedge.net with its plethora of path components
=> Fix three-mesh-bvh import path

src/device/onLoad.js, src/gui/ar/groundPlaneAnchors.js, src/gui/settings.js, src/gui/threejsScene.js
add options `{ dontPersist: true }` when creating a new SettingsToggle to make non-persistent settings. Uses this for the Visualize Groundplane Anchors, and a new setting, Display Origin Boxes, to set visibility to false by default.
Also exposes some APIs that the pop-up settings menu can use to show/hide these.
=> Reliably default certain settings to disabled

src/avatarObjects.js, src/gui/ar/anchors.js, src/gui/ar/draw.js
Ideally we can just check `object.type`, but until I figure out where type is being overwritten we check the name of the object to more robustly identify avatars and ignore them.
=> temporary fix for avatar detection flakiness (check if name includes _AVATAR_)

src/gui/glRenderer.js
Prevents frames from flickering out of existence during difficult moments. Fixes issue where opening the spatial draw tool would cause the camera-vis playback tool to change its winding order or something
=> Glproxy fallback restore

css/index.css, index.html, src/app/callbacks.js, src/app/targetDownloader.js, src/avatar/index.js, src/device/onLoad.js, src/envelopeManager.js, src/gui/ar/areaTargetScanner.js, src/index.js, src/network/discovery.js, src/network/index.js, src/network/realtime.js
- src/network/discovery.js handles heartbeat messages rather than all the logic being in the callbacks.js
- discovery.js has methods to pause/resume processing heartbeats, and to query which objects/servers it is aware of
- adds new Minimize button to envelope UI (currently same functionality as Close button but will update soon)
- adds new status messages while generating the area target
- fixes bug with avatar deletion on pop-up app by sending explicit disconnect message
- targetDownloader.js triggers callbacks that area target scanner can use to more precisely time its events
Remote operator requires a PR for compatibility with the discovery.js module
=> Refactor discovery into its own module + a couple bug fixes and UI updates

src/device/environment.js, src/gui/ar/draw.js
This will let remote-operator-addon prevent tools from rendering before the world mesh loads, despite pop-up-addon saying that rendering is allowed
=> allows multiple modules to request that rendering be suppressed/allowed without overwriting each other 

src/gui/ar/areaTargetScanner.js, src/gui/ar/groundPlaneRenderer.js, src/gui/threejsScene.js, src/network/discovery.js, src/network/index.js
If you're trying to specifically join one world and want to ignore all other world objects, you can call `realityEditor.network.discovery.setPrimaryWorld(ip, id);`
The exact consequences of being the primary world can be changed in future, but there are at least a couple scenarios where I've wanted one world object to be prioritized, e.g.:
- a Join Menu that lets you choose which world to join (e.g. if I scanned a world on my device's 127.0.0.1 in the past but now want to be a virtualizer for one on my laptop's server)
- a remote operator localhost:8081/?world=myWorld URL that specifies which out of all of the worlds in the lab do I actually want to see
=> Allows setting a primaryWorld to ignore other world heartbeats

src/avatar/index.js, src/avatar/network.js, src/gui/threejsScene.js
Before:
After:
I believe this closes the book on Vuforia 10.9 making area targets multi-mesh mapping mayhem
=> Fix merged raycast; Improve avatar pointermove filtering

src/avatar/index.js, src/avatar/network.js
Keeps the avatar object alive while the app is open, even if the avatar isn't moving (e.g on remote operator, if you keep the camera perspective the same). 
Goes with https://github.com/ptcrealitylab/vuforia-spatial-edge-server/pull/600, although neither strictly requires the other
=> Avatar sends keepObjectAlive UDP message on a 10 second interval

src/app/callbacks.js, src/app/index.js, src/device/onLoad.js
before calling getVuforiaReady, call didGrantNetworkAccess to check if the Local Network permissions have been granted to the app.
Requires https://github.com/ptcrealitylab/vuforia-spatial-toolbox-ios-swift/pull/171
=> Visual feedback if no Local Network permissions in iOS settings

css/index.css, index.html, src/gui/threejsScene.js
Chrome appears to not actually care about the canvases' transform/z-index any more so this may require follow-up changes
=> Fix layering of canvases in Chrome

src/avatar/index.js
Stop-gap fix for problem where groundplane collider can be at the wrong height in AR so your laser pointer doesn't hit where you expect it to.
=> Prioritize raycasting against area target mesh before groundplane for avatar lasers

index.html, src/app/callbacks.js, src/app/index.js, src/app/promises.js, src/app/targetDownloader.js, src/device/onLoad.js, src/gui/ar/areaTargetScanner.js, src/index.js
While implementing the `doesDeviceHaveDepthSensor` API, it felt about time to make a cleaner way to call them. Tried not to refactor too many APIs at once, but wrapped a few more in this style for now.
=> Wrap native APIs in Promises for cleaner asynchronous getters

src/app/targetDownloader.js
Error message was occurring if the old version of addNewMarkerJPG was called, since it was referring to the old callback signature which is no longer public.
=> update target downloader to use promise version of addNewMarkerJPG

src/device/index.js
Moves deletion check to the document pointerup event instead of the iframe pointerup event, so it triggers as long as you lift your mouse/finger in the designated region (the right edge of the screen), even if the iframe drifted away from your pointer.
In future I also hope to improve the dragging calculations so that the tools don't drift away from the pointer in the first place, but this should improve robustness either way.
=> fixes trashcan so tool gets deleted even if it drifts away from the pointer

src/device/onLoad.js, src/gui/ar/draw.js, src/gui/ar/utilities.js, src/gui/pocket.js, src/network/index.js, src/sceneGraph/index.js, src/spatialCursor/index.js
1. This adds the ability to add tools at the spatial cursor position. Extra calculations are included to rotate the added tools so that they appear upright relative to the global up vector.
2. I've also added a new helper function, `realityEditor.sceneGraph.convertToNewCoordSystem(point, oldSystem, newSystem)` to help simplify calculations in the future.
3. I also added some functions to the spatialCursor/index.js to snap the position and rotation of the cursor to the overlapping tool iframe.
=> Add tools at the spatial cursor, and snap cursor to overlapping tools

src/device/index.js, src/gui/ar/positioning.js, src/gui/ar/utilities.js, src/sceneGraph/index.js
Dragging now moves tools to the screen (x,y) location while preserving the distance to the camera, rather than translating tools along an imaginary local plane that they sit on, so they move more naturally.
For 2D tools, if you're viewing them from a mostly perpendicular angle, uses the old method to translate them along the plane that they sit on. This way, 2D tools that you've snapped onto a floor or wall will translate precisely along that surface unless you drag them from a fairly different angle.
=> Improved dragging calculations for 3D tools (and 2D tools if viewing from a non-perpendicular angle)

src/device/index.js, src/gui/ar/draw.js, src/gui/ar/positioning.js, src/gui/ar/utilities.js, src/network/realtime.js, src/sceneGraph/index.js, src/sceneGraph/sceneNode.js
PR #302, which improved the dragging of 3D tools, had a couple issues:
1) when physically moving the phone around while holding a tool (in "unconstrained editing mode") the new repositioning method would fight with the old unconstrained method and the tool would flicker.
2) it was still using old calculations for moving 2D tools along their local XY plane, which was using some hacky browser/CSS tricks to do the calculations
This PR adds the following:
1) "unconstrained editing" simply makes the tool a child of the camera instead of freezing its relative matrix, which causes it to move with the camera without fighting with new local matrix values provided by the dragging mechanism
2) new `realityEditor.gui.ar.positioning.moveVehicleAlongPlane` function uses more elegant ray-plane …
=> Tool dragging improvements

src/app/callbacks.js, src/gui/ar/areaTargetScanner.js, src/network/discovery.js
filter out non-world servers from the area target scanning if there's at least one world server that was started using `node server.js --services world`
=> listen to server heartbeats with services list 

src/device/environment.js, src/device/index.js
(memories don't really work anymore but creation is currently available by double clicking the background).
We could bring it back with a little bit of work, but pop-up-addon can disable it too for now, since it doesn't include the memory pocket in the new UI.
=> adds a flag that remote operator can use to disable the creation of memories

src/avatar/draw.js, src/avatar/index.js
- Send infinite beam instead of segment if occlusion mesh hasn't loaded or if your tap is outside the scanned area
- Initialize avatar objects more quickly, and begin to handle errors/timeouts with visual feedback
- Send beam more smoothly, not just on pointer move but also if you move the camera around while holding down
Note: updates to draw.js are less drastic than they might appear – mostly just nesting the rendering in an if-statement to handle infinite rays a bit differently.
=> Various Avatar improvements

src/device/utilities.js, src/spatialCursor/index.js
The `getAllDivsUnderCoordinate` function that the cursor uses was breaking pocket scroll and settings menu, and hurting performance – sets display:none and then resets display:inline to all overlapping elements during the calculation. I'm going to update this function to use pointer-events rather than display in the future, but disabling it for now as a temporary fix since the pointer-events way has some complications with conflicting CSS definitions.
=> disable spatial cursor computations while its toggled off; temporarily remove cursor snapping

src/gui/threejsScene.js
This allows the remote operator to add PositionalAudio instances referencing this listener to create a subtle positional audio effect
=> Add and expose THREE.AudioListener

src/device/environment.js, src/device/onLoad.js, src/network/realtime.js, src/worldObjects.js
Fixes an intermittent bug on Safari/Firefox where the remote operator's content scripts could be loaded later than various initService calls that relied on the remote operator's environment overrides. This directly overrides ar tracking to prevent a flash of the popup. It also adjusts the logic of desktopSocket creation to fix a race condition in a way that may be more universally applicable
=> Cleanup of various remote operator loading race conditions

src/gui/ViewFrustum.js, src/gui/threejsScene.js
Instantiates a ViewFrustum for each virtualizer that sends an update message to the threejsInterface. Discards points that fall within the volume of any of the frustums. Supports up to MAX_VIEW_FRUSTUMS clients at a time, which I currently set to 5.
=> Area target frustum culling shader

src/gui/ViewFrustum.js, src/gui/threejsScene.js, src/humanPose/draw.js
This is a visual experiment based on a discussion with @valentinptc. The idea is to darken the gltf when a virtualizer connects, so that the video stands out more, and to render wireframes in the "shadows" cast by the culling frustum so that we preserve a sense of the geometry. In this approach, rather than using the wireMesh underneath, I render a wireframe effect within the culling frustum using a shader.
@hobinjk-ptc I will be out of office so I'll leave this in your hands if you'd like to merge it or further experiment in this direction.
Requires https://github.com/ptcrealitylab/vuforia-spatial-remote-operator-addon/pull/84
=> frustum shrinks based on maxDepth and renders wireframe inside frustum

src/gui/ViewFrustum.js, src/gui/threejsScene.js, src/spatialCursor/index.js
One last update for the area target shader: based on the similarity between the viewing angle and the virtualizer angle, the mesh wireframe fades in and out. Since you mostly want to see the shadows filled in when you're looking at it from different angles. And when you're perfectly aligned with the virtualizer, you only see the live image data. This minimizes distracting visual effects while you're following a virtualizer.
This PR also includes an update for the spatial cursor to make it follow the remote operator mouse, and to allow it to instantiate new tools at its location. But those effects are toggled off now with two flags: DEFAULT_SPATIAL_CURSOR_ON=false and ADD_SEARCH_TOOL_WITH_CURSOR=false
=> Fade frustum cutout based on viewing angle; prepare spatial cursor for new features

src/gui/glRenderer.js
Introduces new api to prevent calls to
requestAnimationFrame(renderFrame) before they happen. This prevents an issue where a queue of requestAnimationFrame(renderFrame) would build up from the watchdog during the screen sleeping or other scenarios where setInterval would continue while requestAnimationFrame would pause. While renderFrame has logic to prevent this in theory, in practice the entirety of renderFrame would finish (microtasks) before the next request (macrotask) was popped off the requestAnimationFrame queue.
=> Never call renderFrame directly; Use requestAnimationFrameIfNotPending

src/device/index.js, src/device/layout.js
This is necessary to move the trash to the bottom of the screen on the portrait iPhone app, without breaking functionality of the classic app.
=> adds ability to setCustomTrashZone in an addon

src/humanPose/draw.js, src/humanPose/index.js
Fixed a bug in remote viewer when sometimes skeleton is rendered with arbitrary offset (eg. remote viewer is refreshed while an app tracks a person).
=> Fixed a bug in remote viewer

src/envelopeManager.js, src/gui/pocket.js, src/network/availableFrames.js, src/spatialCursor/index.js
`spatialCursor.addToolAtScreenCenter` adds the tool projected onto the surface of the area target, but at the center of the screen, unless the option `{ moveToCursor: true }` is provided, in which case it will position it at the cursor's position. If the center of the screen doesn't raycast against the area target mesh, it will add it floating in the middle of the screen in front of the camera.
Also cleans up/refactors the pocket.createFrame function to use an options object instead of a million optional parameters, and to remove some deprecated functionality.
=> Refactor createFrame; addToolAtScreenCenter works properly

src/sceneGraph/network.js
Rendering of some skeletons at wrong location during replay comes conflicting HumanPoseObject.matrix saved by recorder on server. There are two competing channels which alter this property of the human object on the server - high-frequency transmission of public data of one node (I introduced this one) and low-frequency synchronisation of spatial locations of all objects ( post('/:objectName/matrix') ). The recorder sometimes catches the update from the second one and the matrix there is 'wrong'.
When I was changing the pose streaming previously, I based it on assumption that the matrix property of human pose object is defined wrt. CS of world object (area target). Normally, this matrix just contains 'nose' 3D position in AT CS (identity matrix for rotation part). 
However, the generic …
=> Human pose analytics - intermittent offset skeletons during replay

src/avatar/index.js, src/network/index.js
Problem:
---
In order for frames added by another client to initialize correctly, the reloadObject action message must instantiate them. This adds them to the scene graph, etc.
There was a competing action method, reloadFrame, triggered in response to posting the position of the tool to the server, that might reach the other client before the original reloadObject message was processed that initializes the tool on the other client.
reloadFrame, for some outdated reason, was instantiating an empty Frame() object if the frame didn't exist yet. This would cause reloadObject to not initialize the frame, as it appeared to already exist. Thus the scene node never got added to the sceneGraph, and the tool wouldn't appear on the other client.
I believe this appeared more often more recently …
=> Fix bug where frames were not appearing on other client; tighter avatar synchronization

src/gui/spatialIndicator.js
Since they don't sync across multiple clients yet, let's toggle them off for the upcoming demos until we reach a more final state.
=> temporarily disable spatial indicators

src/network/index.js, src/network/realtime.js
On toolboxedge.net, the responses had outdated values, causing frames not to appear. Question: should we default all getData requests to ignore caching, or only turn it on if the option is specified (which I did in only these two usages, to limit the impact of this change)
---
also reverts the batched update framerate back to 10, in case it would have messed up the poses
=> force ignore potential cacheing of the reloadObject and reloadFrame responses

src/avatar/draw.js, src/gui/spatialArrow.js
Before, the laser pointer arrows were drawn asynchronously in spatialArrow.js, sometimes got cleared unintentionally. This push fixed the issue. Now the arrows for off screen laser pointer should be drawn to the screen no matter what.
=> Laser pointer off screen arrow fix

src/analytics/analytics.js, src/analytics/regionCard.js, src/humanPose/draw.js
Additionally modifies getPosesInTimeInterval to not return duplicate poses where possible. Previously, pulling from clones.all would result in duplicate poses with slightly different timestamps between clones.live and clones.historical.
This new functionality allows the Mark Step button in the spatialAnalytics envelope to function.
=> Allow adding region cards during recording

src/gui/ar/areaTargetScanner.js, src/network/discovery.js, src/network/realtime.js, src/worldObjects.js
Backup method to enable full system capabilities while on a network that doesn't allow UDP messages (e.g. cellular data plan). Remote operator connected to the cloud proxy already uses a web socket interface to listen for beats and action messages; this extends the same logic to all clients (e.g. the phone that made the scan). Also manually adds 127.0.0.1 to the possible servers that this scan can go to, so that it doesn't break while trying to generate a new world object while scanning.
=> Creating a scan works on cellular; listens for beats and action messages with web sockets

css/modal.css, src/app/callbacks.js, src/device/environment.js, src/device/onLoad.js, src/gui/ar/areaTargetScanner.js
Since we have websockets as a backup if no UDP, we no longer need to prevent you from using the app if you hit "No" for iOS Local Network permissions. Also, increases the modal height so that messages aren't cut off (for the remaining Camera and Microphone permissions modals)
=> better handle no UDP permissions; fix height of modal; increase area target scan time 

src/worldObjects.js
Might be responsible for some small bugs, if we've already localized before a module subscribes to the listener
=> trigger onLocalizedWithinWorld immediately if already localized

css/index.css, index.html, src/device/onLoad.js, src/envelopeManager.js, src/gui/envelopeIcons.js
- Opening an envelope will grant it focus
- Minimize button appears if there is a tool that has focus
- Pressing the minimize button removes focus, sending a "blur" event into the tool (to tell it to hide its 2D layer) and setting `pointer-events: none` on the fullscreen iframe
- When blurred, the envelopeIconRenderer renders a placeholder icon at the tool position, using the icon.gif from the tool
- Clicking on the placeholder icon will restore focus to the envelope, sending a "focus" event into the tool (to tell it to show its 2D layer)
- If you've blurred some envelopes, pressing the "close" button will close all envelopes whose contents are visible
Requires https://github.com/ptcrealitylab/vuforia-spatial-edge-server/pull/761, can test with …
=> "Minimize" button removes focus from a tool; renders temporary icon in place

src/worldObjects.js
The previous fix that I was using to get `onLocalizedWithinWorld` to trigger wasn't always working; it seems to be because if you're still on the Setup Metaverse screen when it localizes, the toolbox has a `suppressObjectRendering` flag toggled on, causing `getBestWorldObject` used internally in onLocalizedWithinWorld  to return the _WORLD_local.
This new method has a backup, where it returns the world ID directly used by the `setOrigin` function.
=> fix issue with onLocalized UI getting stuck localizing forever

css/index.css, src/analytics/analytics.js, src/analytics/index.js, src/humanPose/HumanPoseAnalyzer.js, src/humanPose/draw.js, src/humanPose/index.js
This PR supports spatialAnalytics tool minimizing where multiple tools can all load their own history but only the active one controls and interacts with the timeline.
The main change to enable this was making HumanPoseAnalyzer its own file with a bit more compartmentalization. A few functions in src/humanPose/draw.js, most notably the live pose rendering, poke holes in this abstraction but overall it's working in a mostly straightforwards one HPA = one envelope model. I considered extending the current split of live + historical into live + Array<historical> but felt this was a cleaner design overall.
I have not yet tested this with multiple phones
=> Support minimizing multiple spatialAnalytics tools

src/envelopeManager.js, src/gui/recentlyUsedBar.js
Recently-used icons are ordered locally based on last (opened or focused) time. Won't necessarily be consistent across clients, as the focus state is personal to each client. But when you refresh the page it will be consistent with the server version.
Clicking on another recently-used icon will totally close the current envelope if it's a full2D envelope, or just blur the envelope if it has a 3D component.
Goes with: https://github.com/ptcrealitylab/vuforia-spatial-edge-server/pull/773
=> envelopes open in minimized state for others; ru-bar properly updates in response

src/gui/threejsScene.js
Vuforia's authoring mesh includes an untextured mesh for places that it has only geometry data. Removes this untextured mesh from visuals and collision detection to make the mesh look better and keep collision detection accurate. This mesh could be added to the BVH to make it part of the collision detection while invisible but I didn't do that so it would be visually consistent.
=> Remove untextured "mesh_0" from gltf

css/index.css, src/gui/envelopeIcons.js
After adding https://github.com/ptcrealitylab/pop-up-onboarding-addon/pull/43 and https://github.com/ptcrealitylab/vuforia-spatial-core-addon/pull/241, loads the white-line-only icon-foreground.svg files instead of the black-background icon.gifs, and adds a green background with CSS, to make the minimized icons stand out more against the background
=> Make minimized icons green; load svgs instead of gifs

css/index.css, src/envelopeManager.js, src/gui/envelopeIcons.js, src/network/index.js, src/states.js
Moves fullscreen tools to background (z = -10) so we can click on tool icons. If fullscreen tool is full2D (chat and search), moves to foreground (z = 100) so the icons don't render on top of the 2D content.
Since new envelopes can be added/opened while one is focused now, added some code to the focus handlers to close/blur the active envelope when a new envelope enters the foreground.
Also adds a hover visual feedback to minimized icons, so you can tell when you will click on them vs the background.
=> Allow clicking on icons while drawing is open

src/envelopeManager.js
There are some race conditions if you have multiple minimized envelopes and also pass a toolId into the URL. I ran out of brainpower to solve this without adding a timeout before opening, and another timeout before focusing. Probably not 100% robust if on a slow network, but works in the cases where I tried it. In the worst case, it will just open minimized, or close entirely after opening, if another envelope with an open=1 node loads too slowly.
=> if a toolId is present in the URL, attempts to open the envelope when it loads

src/gui/ar/areaTargetScanner.js
With improvements to Vuforia's AT scanning functionality, it is now very difficult for us to run out of RAM during the scanning process.  This removes the limitScanRAM function which, while disabled by default, could be previously toggled on on older devices.
=> Disable limitScanRAM functionality

thirdPartyCode/three/three.module.js
Significantly improves the performance of updateMatrixWorld, previously a large contributor to frame time.
=> Alter three's updateMatrixWorld to not touch hidden objects

src/analytics/analytics.js, src/analytics/index.js, src/analytics/timeline.js, src/humanPose/HumanPoseAnalyzer.js
Most notably prevents race condition where a frame opening automatically while minimized would send a setDisplayRegion to the fallback 'none' analytics, causing the loading of history to happen two times in parallel. Additionally fixes the initial display of data after a recording finishes and cleans up conditions where the timeline would be too narrow due to very short recordings.
=> Miscellaneous Analytics Fixes

src/analytics/analytics.js, src/analytics/index.js, src/humanPose/spaghetti.js
Spaghettis were previously having their active state modified by spaghettis in other analytics sessions. They were also messing with the timeline and receiving pointer events in those cases. This fixes those issues.
=> Multi analytics spaghetti fix

src/app/index.js, src/humanPose/index.js
Added mitigation measure for occasional miss of UDP action message about deletion of human object on server. One can use a toggle to switch off human tracking and now also wipe out local human object hanging on device.
It has one minor issue in the case when human tracking is quickly disabled and enabled. In that case, there are two human objects from the same device on server (eg. _HUMAN_deviceGA42d823_pose1__G4ckapkg4ly, _HUMAN_deviceGA42d823_pose1__pg9h11b77sw). However, once the stale object cleaner removes the older one which is already wiped out on the device, this causes deletion of both and new human object is created quickly. This is due to the behaviour of deleteObject(objectKey) on server which deletes the desired object but also calls utilities.deleteObject(). This uses a name …
=> Added mitigation measure for occasional miss of delete on server

src/avatar/index.js
Goes with https://github.com/ptcrealitylab/vuforia-spatial-edge-server/pull/805
Includes name, sessionId, and providerId, in case any of these are useful for the tool.
Requires an update to the pop-up-onboarding-addon to fetch the user name from the metaverse manager...
=> implements the getUserDetails tool API by setting avatar user name

src/device/environment.js, src/gui/ar/areaCreator.js, src/gui/ar/positioning.js, src/gui/threejsScene.js
It seems about time to allow the remote operator to work on a phone or tablet web browser. Adds initial support to load the remote operator in an iPhone/iPad safari browser.
- uses `isARMode()` instead of `isDesktop()` to allow the remote-operator-addon to better determine whether to load remote operator features or AR features
- adds some performance improvements, mainly allowing the mobile browsers to use the default gltf material instead of the advanced material, because this improves the FPS from ~15 to 60 on my device and we aren't really using the frustum culling right now.
See also https://github.com/ptcrealitylab/vuforia-spatial-remote-operator-addon/pull/119 (adds multitouch controls for the camera) and https://github.com/ptcrealitylab/pop-up-onboarding-addon/pull/69
=> Mobile remote operator

src/analytics/analytics.js, src/analytics/index.js, src/analytics/timeline.js
This enables creating and viewing patches as a part of the Analytics workflow. During recording, "Mark Step" saves a patch at that moment in time to provide spatial context. Playback on the timeline then displays this patch when the cursor time overlaps with its approximate creation time.
=> Analytics: Patches support

src/envelopeManager.js, src/gui/ar/draw.js
Not worth merging ahead of the demo but this fixes my drag-and-drop errors.
Pointer events get re-enabled if the tool opens in fullscreenFull2D, as in that case the overlay div is removed and the iframe itself needs to receive pointer-events again.
(necessary on localhost. not necessary if you load remote operator by IP, for some unknown reason)
(the deleteNode.bind() is a separate error I noticed, unrelated to drag-and-drop)
=> normalize matrix3d transforms to fix chrome bug with dragover events on localhost

src/spatialCursor/index.js
This has been bugging me for awhile – following a video in first person mode would cause the spatial cursor and the virtualizer video to z-fight since they both turn off depthTest and had the same renderOrder.
Before update:
After update:
=> increase renderOrder of spatial cursors so they don't z-fight with 2d virtualizer video

src/network/availableFrames.js
Decreases the number of network requests the system makes when it starts up – since we don't show the old pocket anymore, we probably don't need to download all of the icon.gif files for the tools we never see. As a side effect, eliminates some error messages from the console that always show up on launch (depending on which addons/tools you have)
=> dont download all icon.gif files if UI is overridden (e.g. with pop-up-addon)

css/index.css, src/envelopeManager.js
I think the UI looks cleaner if they are hidden while the background is blurred, since they don't blur and sometimes interfere with the focused tool's content.
Example before:
Example after:
=> hide other tools and icons in the background when a full2d tool is open 

css/index.css, src/envelopeManager.js
Improvement based on @ptc-mklaudiny's observation that the time-series graph stops ticking forward while the blurred background is hiding it in the previous implementation (https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/525).
A similar side effect seems to be that a proxied gl context doesn't render while display:none is applied to the corresponding iframe, so I didn't need to specifically hide the glcanvas in the previous implementation.
This solution uses visibility:hidden on the iframes, but as a result also needs to apply visibility:hidden to the glcanvas.
=> Fix bug in previous implementation of "hidden by blurred background"

src/spatialCapture/SpatialPatchCoordinator.js
This should fix the issue you and Valentin discovered – can you test? Feel free to merge it if it works
=> fix the restoration of the virtualizer visibility after you press P to clone patches

css/index.css, src/device/onLoad.js
Makes the error that shows up due to uBlock developing a hatred for the phrase "analytics.js" last longer onscreen so that users (hopefully) notice it and come to us for education. Also moves the timeline down to make more space on short screens.
=> Analytics adjustments

css/index.css, src/gui/ar/draw.js, src/gui/envelopeIcons.js
This has nagged at me for awhile but I never tracked down what was causing it.
Prevents icons / CSS-3D transformed tools from rendering when you zoom past them – the way we manipulate the matrix in the render loop currently causes them to show up upside-down. Sets display:none when conditions are met. Only does this on non-fullscreen tools, which ensures that 3D content or an active envelope doesn't hide when you move the camera.
Note: I added a new CSS class `elementBehindCamera` to tag these with instead of re-using `outsideOfViewport` because outsideOfViewport has some complicated logic attached that involves reloading the iframe when it moves in and out (as calculated by `realityEditor.gui.ar.positioning.canUnload`) which is disabled on desktop, and I don't think we need to …
=> Hides non-fullscreen tools/icons when their MVP matrix has negative matrix[14]

src/gui/ar/draw.js, src/gui/envelopeIcons.js
In my enthusiasm to improve the billboarding for remote operators (https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/557) I forgot to test how it impacts rendering in AR, and now I've realized that the new method I used (basically just setting rotation to identity) doesn't work on AR because when you rotate the phone (like a steering wheel) the icons rotate with it. I've tried various maths for getting the perfect transform in AR but can't quite get it to avoid singularity behavior when you view from the top. Something something quaternions but I don't have the headspace for that right now.
This reverts to the old method on AR but keeps the new implementation for desktop.
=> revert to old billboarding on AR devices; use new method on desktop

src/envelopeManager.js, src/humanPose/draw.js
I added `if (!realityEditor.motionStudy.getAllHumanPoseAnalyzers) return;` because I think `getAllHumanPoseAnalyzers` is undefined and this function is able to be triggered by pressing the H keyboard shortcut. Not sure what the intended functionality is.
=> Misc error guards and whitespace cleanup

src/app/callbacks.js, src/app/index.js, src/app/promises.js, src/app/targetDownloader.js, src/constructors.js, src/gui/ar/draw.js, src/gui/ar/frameHistoryRenderer.js, src/gui/ar/moveabilityOverlay.js, src/gui/ar/positioning.js, src/gui/ar/utilities.js, src/gui/screenExtension.js
New app version reports tracked targets using their targetId, rather than objectId. This method is still backwards compatible with old app versions or object versions which don't have a targetId.
Goes with https://github.com/ptcrealitylab/vuforia-spatial-toolbox-ios-swift/pull/555
=> updates receiveMatricesFromAR to be compatible with targetId tracking method

src/app/index.js, src/app/promises.js
New promise versions of setPause and setResume that resolve when pause/resume is complete, with success status.
These can be used to ensure that the app has finished pausing/resuming AR before continuing, since the regular app function calls aren't guaranteed to be synchronous.
=> app.setPause and app.setResume can take a completionHandler callback

css/index.css, css/modal.css, src/avatar/draw.js, src/avatar/index.js, src/gui/modal.js
Brings up a modal to edit your username. Instantly propagates to other clients when you hit submit. Tested working on iOS app too. Saves name in browser localStorage and uses as default when you refresh the page if you're an anonymous user. Your signed-in username in the Manager overrides the saved value if you're signed in (the next time you refresh the page, but you can still edit for this session).
Fixes Issue #614
=> Click on icon to edit your username

src/gui/threejsScene.js
It brings a bit of drama to the scan lighting but we're not in the business of drama
=> Remove ACES filmic tone mapping

src/humanPose/AccelerationLens.js, src/humanPose/HumanPoseAnalyzer.js, src/humanPose/HumanPoseAnalyzerSettingsUi.js, src/humanPose/HumanPoseRenderInstance.js, src/humanPose/MotionStudyLens.js, src/humanPose/OverallRebaLens.js, src/humanPose/Pose.js, src/humanPose/PoseObjectIdLens.js, src/humanPose/RebaLens.js, src/humanPose/TimeLens.js, src/humanPose/constants.js, src/humanPose/draw.js, src/humanPose/rebaScore.js, src/motionStudy/motionStudy.js, src/motionStudy/regionCard.js
General idea is to filter out joints which have a low confidence. The confidence is essentially a visibility score we get from mediapipe for limbs (not torso and head). The filtered joints and adjacent bones are not displayed. Also, some analytics calculations are affected by this (eg. REBA score of a leg should not be calculated if ankle joint is filtered. We then default to the lowest score 1). However, it is not relevant for all lens (Waste/Value does not care about pose directly).
I tried to make the changes not very invasive and shared by all relevant analytics lens. All joints and bones in Pose class has new valid attribute which is calculated based on a given confidence threshold (or recalculated when the threshold is changed on the fly). This attribute is used to show/hide body …
=> Human tracking filtering low confidence joints

src/gui/threejsScene.js, src/splatting/Splatting.js
Prevents you from accidentally displaying a black screen with an error message if you hit the comma key before the splat has been loaded properly.
Also moves cursor gsToggleActive to better location – (removes lines from here https://github.com/ptcrealitylab/pop-up-onboarding-addon/pull/128)
=> disable the comma keyboard shortcut unless you've already shown the splat at least once

src/avatar/index.js
Fixes 2 problems that were happening after you've resized the window at least once:
1. Properly clears the top edge of the screen of the spatial pointer graphics
2. Properly aligns the endpoint of the spatial pointer with your pointer position
Both are fixed by removing references to the menuBarHeight that added a vertical offset to the canvas, and just making the canvas occupy the entire screen and clear the entire screen, removing any chances for misalignment.
Before:
After:
=> Fix the Spatial Pointer canvas's vertical offset

css/index.css
Puts avatar icon container above drawings and fullscreen chat.
Fixes issue https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/issues/673. Fullscreen tools have z index 100, but I put it even higher to give it additional priority.
Before:
After:
Before:
After:
=> move avatar container z index above the fullscreen tool z index

src/device/onLoad.js, src/gui/settings/setupSettingsMenu.js
I missed one part of the onLoad.js that should have been moved in PR #675. Moving it fixes a bug / linting error that doesn't surface in the pop-up version of the app.
=> move shouldShowIntroModal logic from onLoad.js to setupSettingsMenu.js

src/spatialCapture/Shaders.js
Previously depthTest would be disabled in first person mode which drew correctly in the previous system. Now with the depth-based system replacing layers, depthTest is required to draw above the ground plane visualization.
Adjacent to this, the current state draws first person video above the pose renderers and it would be nice (but not required) to be able to see the pose renderers in first person if you have any free time in search of a use @ptc-rdeleeuw
=> Always enable depthTest on CameraVis shader

src/device/videoRecording.js, src/gui/settings/setupSettingsMenu.js, src/worldObjects.js
Much ado about sweet wine
Fixes one exception from getPort using `object`, not `object.port`
Fixes some swift-side issues where the missing port would cause pose tracking's connection to fail
=> Clean up various uses of `port` and APIs that want `port`

src/motionStudy/motionStudy.js
Bug happens if you add it, minimize it without recording anything, and drag the icon to the trash. The video player is null in that case.
=> fixes bug where analytics tool doesnt delete properly in some cases

css/index.css, src/motionStudy/motionStudy.js
Still need to think of a way to determine if the raw, oriented-relative-to-vuforia's-idea-of-the-world video came from portrait or landscape recording but this at least flips iPad video while laying the groundwork
=> Add part of solution for portrait videos; Flip iPad video to match testflight orientation

src/gui/ar/draw.js
iOS sends a ton of matrix update messages which in turn redraw. The app can't keep up with the stream so this reinstates previous behavior of discarding updates if a new frame hasn't been rendered yet.
=> Re-enable frameNeedsToBeRendered in iOS app

src/gui/sceneCapture.js, src/gui/threejsScene.js, src/splatting/Splatting.js
Goes with: https://github.com/ptcrealitylab/vuforia-spatial-remote-operator-addon/pull/202, to enable getting a thumbnail image of the scene. Just doing canvas.toDataURL at arbitrary moments elsewhere in the code may result in an empty image in between canvas draw calls.
=> Capture canvas screenshot (for camera perspective memory bar)

src/avatar/index.js
Fixes the bug we noticed where the pointer beams weren't being sent when collaborating on a CAD model in an empty world, because the avatars were relying on the mesh having loaded in order to get into the logic of the raycast function.
I also commented out the `realityEditor.network.postAiApiKeys` as that function doesn't exist anymore (with that name), so sometimes the pointer synchronization was being broken by that line being triggered in the public data synchronization of avatars. I don't know in the long term if we want to keep that mechanism in there or remove it entirely – I think we discussed before that sending the keys like that is a security problem, but I didn't want to take out that syncing mechanism entirely if you're still using it @Steve-KX-RL
=> calculate avatar beam endpoint using groundplane even if no occlusion object

css/index.css, src/avatar/index.js, src/device/index.js, src/gui/ar/positioning.js, src/network/index.js, svg/draggable-handle-white.svg
I've been meaning to merge this in for the better part of a year, but it always got mixed up in other PRs that I didn't end up merging. This allows for the mashup embed in the thingworx tool, by adding an API that lets you turn the tool into a floating window with a draggable bar above it, and removing the overlay div from the iframe so that you can naturally scroll/type/click on its contents. The iframe gets temporarily covered/protected when you perform certain gestures outside of the iframe, such as rotating the camera or starting the pointer, so that those gestures don't get interrupted if your cursor passes over the iframe.
To use this in a tool, call `spatialInterface.setFull2D(true, { showWindowTitleBar: true });`
=> Non-fullscreen full2D mode for tool, with draggable title bar

src/gui/shaders.js, src/gui/spatialArrow.js, src/gui/spatialIndicator.js, src/spatialCursor/index.js, src/splatting/Splatting.js, src/utilities/MathUtils.js
Old GS raycasting method has a fundamental flaw which makes calculating cursor world position dependent on screen aspect ratio, specifically only accurate when screen is 1:1. Now introducing a new way to get raycast position. We use the camera space depth to compute the offset between camera and raycast position, and converting it back to world space. The result is a smooth & accurate spatial cursor, always at the center of mouse cursor, regardless of the screen aspect ratio.
https://github.com/user-attachments/assets/4642e6dc-e7f5-4b1c-8ce6-7d4f656698a6
=> Fixed GS raycasting cursor jumping around bug + all math functions refactor

src/app/targetDownloader.js
Prevents the session from breaking when trying to load an unusually large area target, e.g. this scan of the 17th floor
=> Error handling around navmesh write to local storage

src/avatar/index.js, src/avatar/network.js
Reduces the rate that you send your avatar position to the server; uses 10 fps normally, but reduces it to 1 fps if you're following another user's avatar (referred to in the code as `lockOnMode`). This is to prevent everyone from spamming the server at the same time while a large group is following a single avatar that's moving around.
Works best in combination with https://github.com/ptcrealitylab/vuforia-spatial-edge-server/pull/1125
=> Optimize network bandwidth used while in avatar following mode

src/gui/ar/videoPlayback.js, src/spatialCapture/Shaders.js
For complex iOS-side reasons the videos are upside-down.
=> Invert video player shader

src/avatar/iconMenu.js
Fixes bug where `myId` starts out null, so when the page is loading it might look like other users are following you if they aren't following anyone (because their lock on ID is also null).
=> hide UI that says X users are following you, until your avatar has finished initializing
