ptcrealitylab/vuforia-spatial-toolbox-userinterface

css/modal.css, index.html, src/device/onLoad.js, src/gui/modal.js, src/gui/settings.js
implemented using the modal.js class I wrote for the git commit feature, but with different CSS styles and a header field.
Note: latest iOS app version is required for these links to open in safari instead of in-app
=> Intro instructions

src/gui/settings/foundObjects.html
Adds the ability to upload an image target to an anchor object on the server directly from the app.
=> Add Image Target Upload

src/gui/crafting/blockMenu.js
previously there were at most 6 rows of blocks allowed, now it calculates the number of rows based on how many blocks it loads from the server
=> fix the logic block menu so it can hold more than 24 blocks

package-lock.json, src/device/layout.js
Resolves #110 
iPhone XS previously wasn't included among phones with notches and iPhone 11 miscalculated the notch size.
=> iPhone notch fix

src/gui/settings/foundServers.html, src/gui/settings/index.html
Adds ability to add objects to detected servers from within the app.
=> Add object functionality

src/device/index.js
not sure why this is happening, but realityEditor.device.onElementTouchMove gets triggered repeatedly if you hold your touch in the same position (and thus sends pointer move events into the tools' iframes)
unrelatedly, also increases touch move threshold for logic nodes to make them easier to move.
=> prevent duplicate pointermove events from triggering if the touch position didnt actually change

src/gui/crafting/blockMenu.js, src/gui/settings/foundObjects.html
Supersedes #133 with a couple minor fixes
=> Block categories

src/gui/spatial/index.js, src/network/index.js
This fix makes sure that the p5 loop, webgl context and very much all p5 is removed when not in use and reloads once required.
=> fixed an issue where p5 takes resources even if its not in use.

index.html, src/app/targetDownloader.js, src/device/environment.js, src/gui/ar/anchors.js, src/gui/ar/draw.js, src/gui/ar/positioning.js, src/gui/ar/utilities.js, src/gui/pocket.js, src/gui/screenExtension.js, src/gui/settings.js, src/gui/settings/index.js, src/gui/spatial/index.js, src/index.js, src/moduleCallbacks.js, src/network/availableFrames.js, src/network/index.js, src/network/realtime.js, src/sceneGraph/index.js, src/sceneGraph/network.js, src/sceneGraph/sceneNode.js, src/worldObjects.js
- Upload stale parts of sceneGraph to server using new sceneGraph/network.js (via the objects' `.matrix` property)
- Various adjustments to fix scene graph bugs that appeared when running in remote operator desktop environment
- Various code cleanups (including removing a lot of now-unnecessary console.logs)
(Compatible with current server version, although a future server PR will make better use of this data)
=> Scene graph server synchronization and compatibility with remote operator 

css/index.css, css/modal.css, index.html, src/app/callbacks.js, src/app/index.js, src/device/distanceScaling.js, src/device/environment.js, src/device/index.js, src/device/onLoad.js, src/device/tracking.js, src/device/utilities.js, src/envelopeManager.js, src/gui/ar/anchors.js, src/gui/ar/draw.js, src/gui/ar/index.js, src/gui/glRenderer.js, src/gui/modal.js, src/gui/pocket.js, src/index.js, src/network/availableFrames.js, src/network/frameContentAPI.js, src/network/index.js, src/sceneGraph/index.js, src/sceneGraph/network.js
Various bugs and features from the task list:
- Adds support for new spatialInterface APIs (tools can specify where they prefer to attach to, tools can subscribe to their position in the world)
- Supports node's `invisible` property
- Adds settings toggle for hiding/locking anchor object positions
- Improves tracking reliability and visual feedback by supporting limited tracking status and displaying loading UI when app closes and opens
- Bug fixes
=> Improvements for complex nodes demo

src/gui/glRenderer.js
Removes an unused memory hog of a debug variable and cleans up a bit of code
=> Gl perf improvements

src/device/tracking.js, src/network/index.js, src/sceneGraph/index.js
adds sceneGraph.setLoyalty and changes the implementation of the attachesTo tool API to use this instead of changing the tool ID. also implements the errorNotification tool API
=> Implements sceneGraph.setLoyalty and spatialInterface.errorNotification

src/network/availableFrames.js
Addresses issue #157 
With the introduction of the scenegraph, the previous method for prioritizing other world objects over the world_local (which relied on comparing their distances) doesn't work, so the wrong icon file was sometimes being displayed in the pocket menu. I updated the distance comparison to treat the world_local as infinitely far away.
=> fix which tools get loaded into pocket when looking at world object

src/gui/ar/areaTargetScanner.js
Going to find a better solution for managing the z-indices in the future...
=> Z index for area target stop button

src/gui/ar/draw.js, src/network/index.js, src/states.js
since browsers don't render negative values anymore. Made these changes temporarily elsewhere but think they got lost.
=> changes to make sure tools are positive-z on remote operator

src/device/environment.js, src/device/keyboardEvents.js, src/gui/ar/groundPlaneAnchors.js, src/gui/threejsScene.js, src/network/index.js
- fix keyboard event propagation (in conjunction with PR for remote operator add-on)
- surface anchors don't conflict with settings menu scrolling
- correctly post tool positions to server when moved with surface anchors
- option to hide the origin cube
=> Metaverse demo bugfixes

css/index.css, index.html, src/device/layout.js, src/gui/ar/draw.js, src/gui/pocket.js, src/gui/settings/index.js, src/sceneGraph/index.js
Proper scrollbar, tap once to select and show info, tap another time to add, drag anywhere to scroll.
The code is a mess please don't look too closely 👀
=> Pocket UI improvements

src/device/distanceScaling.js, src/device/index.js, src/device/touchPropagation.js, src/envelopeManager.js, src/gui/ar/groundPlaneAnchors.js, src/gui/ar/index.js, src/gui/memory/nodeMemories.js, src/gui/pocket.js
- provides API that remote operator can access to filter out which objects get prioritized for adding new tools to them
- provides API that remote operator can access to trigger the scaling feature without pinching with 2 fingers
- small bugfix for new pocket UI
- hides groundplane anchors for tools hidden inside closed envelopes
- adds pointer move events to pocket to detect if mouse hovers over a tool icon (for mouse-based devices .e.g desktop)
=> Misc UI improvements & support for new remote operator features

src/gui/ar/lines.js, src/gui/threejsScene.js
While drawing a new link, end weight will match start weight.
=> Link drawing weight

css/settings.css, src/app/callbacks.js, src/device/onLoad.js, src/gui/ar/areaTargetScanner.js, src/gui/modal.js, src/gui/settings.js, src/gui/settings/foundServers.html, src/gui/settings/index.js, src/network/availableFrames.js, src/network/index.js
Allows viewing toolbox edge agent addon settings and sharing links
Communicates with local server as a normal server
Enables choosing between local and remote scan destinations for area target
=> Standalone Server Support

index.html, src/gui/threejsScene.js, thirdPartyCode/three-mesh-bvh.module.js
Fixes performance issues when raycasting against large gltf models
=> uses three-mesh-bvh to speed up raycasts

src/device/index.js
caching the occlusion object for raycasts and not calling computeVertexNormals on every touchevent fixes all the issues with performance
=> Silky-smooth drawing tool performance via optimized raycast

src/gui/ar/areaTargetScanner.js
Pretty sure this is all that's required. I don't have my environment set up to fully test it.
=> properly detects world objects saved on 127.0.0.1

src/avatarObjects.js, src/network/index.js
On the proxy we get fancy with 204 status codes. network.getData does not enjoy this
=> Avatar object 🤝 Network getData API

src/avatarObjects.js
Also increases size of sphere at the end of the laser pointer, to be more visible
=> Allows avatar object debug mode to be toggled

src/humanPose/draw.js, src/humanPose/rebaScore.js, src/humanPose/utils.js
Notably changes JOINT_CONNECTIONS to be a bit more organization-friendly
=> rebaScore support

src/gui/ar/draw.js, src/gui/ar/positioning.js, src/network/index.js
Goes with https://github.com/ptcrealitylab/vuforia-spatial-edge-server/pull/606
=> adds support for the tool API subscribeToObjectsOfType(type, callback)

index.html, src/app/callbacks.js, src/avatar/utils.js, src/gui/ar/anchors.js, src/gui/ar/meshLine.js, src/gui/threejsScene.js, src/humanPose/draw.js, src/humanPose/index.js, src/humanPose/rebaScore.js, src/humanPose/utils.js, src/index.js, src/network/index.js
Update HumanPoseRenderer to properly render the pose joint tools.
Works in AR and on remote operator (can comment out `this.drawSkels(skels);` in remote-operator-addon RealityZoneViewer.js to test without rendering double)
=> Render poses+REBA directly from Object data structure

src/gui/ar/draw.js, src/network/index.js
Looks quite nice, imo!
Goes with https://github.com/ptcrealitylab/vuforia-spatial-edge-server/pull/613
=> implements billboarding effect when spatialInterface.setAlwaysFaceCamera API is called

src/gui/threejsScene.js, src/humanPose/draw.js, src/humanPose/index.js
=> Human pose history spaghetti

.gitignore, css/index.css, src/analytics/analytics.js, src/analytics/index.js, src/analytics/regionCard.js, src/analytics/timeline.js, src/gui/ar/meshPath.js, src/humanPose/draw.js, src/humanPose/spaghetti.js
It is likely that regioncards aren't going to exist in a pinned form so some of these changes are going into the wind
=> Even more analytics api work; Invisible spaghetti finally unhoverable

src/avatar/draw.js, src/avatar/index.js, src/avatar/network.js, src/avatar/utils.js, src/humanPose/index.js, src/spatialCursor/index.js
Uses avatar's publicData channel to synchronize the positions of all the spatial cursors across clients. Cursors on other clients look similar, but are more transparent.
=> Spatial cursors are visible to all clients; positions update in realtime; colors match avatars

css/index.css, src/envelopeManager.js
We didn't end up implementing the concept of "spatial sessions" so I'm removing this button for now.
=> adds flag to disable minimize [-] button next to the exit [x] button when envelopes are open

src/device/keyboardEvents.js, src/spatialCursor/index.js
1. Smooth spatial cursor direction
2. Cursor always facing towards the camera
3. Added in & out animations cursor don't intersect with the AreaTarget mesh
=> Spatial cursor indicator arrow matching avatar color

src/spatialCursor/index.js
worldIntersectPoint is scoped to the file now so the previous implementation stopped working
=> fix addToolAtScreenCenter when you tap on a tool button

src/gui/ar/meshPath.js, src/humanPose/draw.js, src/humanPose/index.js, src/humanPose/spaghetti.js, src/humanPose/utils.js
Now creates spaghetti all at once rather than regenerating it repeatedly one additional point at a time
=> Performance improvements for history spaghetti generation

css/modal.css, src/gui/ar/areaTargetScanner.js
Going to rewrite this all more cleanly when Keranie and I do another pass on the UI, but for now this works to make the area target generation modal look ok on iPad too.
=> Area Target Generation modal responsive design

src/avatar/index.js
This seems to work in the couple times I've tested it, but ideally I should test it more.
If the server deletes your avatar (tried testing by triggering a breakpoint in my code for 15 seconds), this will cause the client to ask the server to create its avatar again, rather than only creating it one time when the app launches.
=> creates your avatar again if the server deletes it while you were inactive

src/gui/ar/groundPlaneRenderer.js, src/gui/threejsScene.js, thirdPartyCode/THREE.InfiniteGridHelper/InfiniteGridHelper.module.js
These commits should belong to Steve but they needed to be extracted from some unfinished work he had. Adds in the Holodeck-style infinite grid
=> Infinite Grid

src/avatar/draw.js, src/gui/spatialArrow.js, src/gui/spatialIndicator.js, src/gui/threejsScene.js, src/spatialCursor/index.js
1. Draw off-screen arrow at laser pointer position
2. Fix beacon bad normals and have them always point towards the camera side
3. GUI experiment -- spatial cursor click -> inner circle expand animation
=> User Interface GUI updates

css/index.css, src/analytics/analytics.js, src/analytics/regionCard.js, src/humanPose/HumanPoseRenderInstance.js, src/humanPose/HumanPoseRenderer.js
Not tooo happy with the scrollbar on a transparent container, feels like an easy future win to make that look less bad
=> Analytics polish

src/gui/ar/groundPlaneRenderer.js
This will support a "Dark Mode" toggle in the remote operator
=> option to update the groundplane grid color and thickness

src/gui/threejsScene.js, src/spatialCursor/index.js
1. Fixed update() twice bug
2. Replaced requestAnimationFrame() with realityEditor.gui.ar.draw.addUpdateListener()
=> Spatial cursor flickering bug

src/humanPose/draw.js, src/humanPose/index.js
Related to server change - https://github.com/ptcrealitylab/vuforia-spatial-edge-server/pull/749
=> Issue with null value of parent property of human object

css/index.css
so the fullscreen chat tool appears in front of the drawings
=> render the tool iframes on top of the glcanvas

css/index.css, src/gui/recentlyUsedBar.js
- updated UI for mobile and desktop
=> Ru tools UI update

src/envelopeManager.js
Missed a step the first time the buttons lazily instantiate
=> Fix updateExitButton refactor

src/gui/threejsScene.js
Updated to support toggling on/off frustum cutouts from the area target shader
=> properly update material numFrustums uniform when a frustum is removed

css/index.css, src/gui/recentlyUsedBar.js
After a chat with Valentin, I increased the speed of the animation to 60ms (can modify `this.hoverAnimationDurationMs = 60;` to change this), down from the ~160ms I tested with earlier, to make the animation super subtle. We can adjust this later if we want the animation more or less visible.
=> Animated lines from recently used icons to their corresponding tool

css/index.css, src/envelopeManager.js, src/gui/recentlyUsedBar.js, src/network/index.js
some UX and bugs, necessary for upcoming PR for pop-up addon
=> smaller minimized icons; callbacks for full2D toggled; more robust z-index of full2D tools

src/humanPose/HumanPoseAnalyzer.js, src/humanPose/constants.js, src/humanPose/index.js
Cherry-picked this out of my ongoing analytics work to provide a fix for poses not appearing on mobile (it should work standalone but I've only tested it with all of my other unrelated work)
=> Disable loadHistory on mobile; Respect recordingClones; Reduce max poses on mobile

src/app/index.js
Related to main PR - https://github.com/ptcrealitylab/vuforia-spatial-toolbox-ios-swift/pull/371
=> Stationary device mode

src/analytics/AnalyticsMobile.js, src/analytics/analytics.js, src/analytics/index.js, src/analytics/regionCard.js, src/analytics/timeline.js, src/humanPose/draw.js, src/humanPose/spaghetti.js
Simplifies AnalyticsMobile implementation
Fixes various state issues with focus/blur/open/close
Enables reuse of previously loaded data (no more reloading the entire mercedes dataset every time you open the tool)
=> Create new Analytics for every spatialAnalytics tool

src/spatialCursor/index.js
- new functions added to place new tools at specific locations in model
duplicates of existing functions were created to avoid conflicts in other parts of the codebase. addToolAtSpecifedCoords could eventually be merged with addToolAtScreenCenter.
- addToolAtSpecifiedCoords is a copy of addToolAtScreenCenter
- getOrientedCursorAtSpecificCoords is a copy of getOrientedCursorIfItWereAtScreenCenter
=> Add tool at specified location

src/humanPose/HumanPoseAnalyzer.js, src/humanPose/spaghetti.js
(tagging Ben to review since Dan is on pto)
=> Analytics: Fix spaghetti line break logic, avoid array recreation

src/humanPose/HumanPoseAnalyzer.js
This reverts commit bba234953c805c6bf07a93e2d53290639980fc51.
=> Revert "Re-reverting hpa pretending to be spaghetti"

src/gui/recentlyUsedBar.js
Keeps every icon in recently used bar then uses these hidden icons to replace deleted icons when necessary
=> Upon deletion fills recently used bar

src/app/index.js, src/app/promises.js
Requires https://github.com/ptcrealitylab/vuforia-spatial-toolbox-ios-swift/pull/410
=> adds swift api to getManagerBaseURL programmatically

src/device/onLoad.js, src/gui/modal.js, src/network/index.js, src/spatialCursor/index.js
- Refactored notification that file upload can use
- Listener for when nodes get added, so file upload can write to node public data after the node has been created
- Public functions for manipulating spatial cursor while file is being dragged into the space
=> Drag and drop files

src/network/index.js
for toolsocket to work on externally hosted tools
=> pass parent location into tool iframes, 

src/avatar/index.js, src/avatar/network.js
=> Avatar sync update

src/gui/glRenderer.js
=>  Save and restore bindVertexArray calls;  Warn on missing texture bind 

src/app/navmeshWorker.js, src/gui/ar/draw.js, src/gui/threejsScene.js, src/network/frameContentAPI.js, src/sceneGraph/index.js
Implements the APIs added in https://github.com/ptcrealitylab/vuforia-spatial-edge-server/pull/891
Also moves the floorOffset to always be at the lowest point in the mesh, and adds a couple minor optimizations to the camera update loop.
=> implements new sendCoordinateSystems API and adds a few optimizations

src/app/targetDownloader.js, src/network/realtime.js
Required to fix https://github.com/ptcrealitylab/vuforia-spatial-edge-server/pull/909
=> Loosen comparison of target ip if one ip is localhost

src/gui/threejsScene.js
Adds back the fancy loading animation (with frustum culling still disabled)
Fixes issue where on larger scans the white mesh areas would show up
=> Miscellaneous threejsScene fixes and improvements

css/index.css, src/analytics/AnalyticsMobile.js, src/analytics/analytics.js
This nearly got lost in the churn of branches
=> Analytics: Upload step labels; Show step labels

src/cloud/index.js, src/worldObjects.js
App update not necessary, only a change on toolboxedge.net
=> Don't load world object on proxy

src/cloud/index.js, src/gui/ar/positioning.js, src/gui/threejsScene.js, src/measure/clothSimulation.js, src/network/availableFrames.js, src/network/index.js, thirdPartyCode/toolsocket/index.js
Toolsocket has been updated to a more recent version, and the userinterface now properly connects to the cloud proxy websocket using `ws` or `wss` as appropriate, allowing for local cloud proxy connections
=> Stability Improvements

src/app/index.js, src/app/targetDownloader.js, src/device/onLoad.js, src/device/videoRecording.js, src/gui/crafting/nodeSettings.html, src/gui/screenExtension.js, src/gui/settings/foundObjects.html, src/gui/settings/foundServers.html, src/network/index.js, src/network/search.js, src/oauth/index.js
if we run the server in https these internal links will also have to ask for https
depends on:
https://github.com/ptcrealitylab/vuforia-spatial-remote-operator-addon/pull/156
https://github.com/ptcrealitylab/pop-up-onboarding-addon/pull/113
https://github.com/ptcrealitylab/vuforia-spatial-edge-server/pull/997
https://github.com/ptcrealitylab/vuforia-spatial-toolbox-ios-swift/pull/593
=> Enable https

css/statusPage.css, index.html, src/avatar/network.js, src/device/onLoad.js, src/index.js, src/network/realtime.js, src/statusPage/StatusCheck.js, src/statusPage/index.js, src/worldObjects.js
Adds a status page (toggleable by clicking the ping indicator added by pop-up-onboarding-addon).
Also fixes a few sources of dropped messages as well as too-many-messages.
=> Status page

css/index.css
=> Make regionCard buttons always visible

.gitignore, src/gui/ar/groundPlaneRenderer.js, src/gui/threejsScene.js, src/spatialCapture/CameraVisPatch.js, thirdPartyCode/THREE.InfiniteGridHelper/InfiniteGridHelper.module.js
simplify the render loop by eliminating the need for layers, rendering the whole scene at once instead of multiple times with different layers
depends on:
https://github.com/ptcrealitylab/vuforia-spatial-remote-operator-addon/pull/158
=> Single layer grid

src/gui/scene/Renderer.js
adds functionality to the render class that makes three.js manage the update cycle (needed for WebXR compatibility)
=> Threejs controlled animation loop

src/humanPose/rebaScore.js
Fixes to REBA calculation to adhere better to original definition.
Tuned some thresholds which are not explicitly defined by REBA.
Adjusted coloring of some body parts based on their reba score.
=> Human tracking reba score fixes

css/index.css, src/gui/ar/videoPlayback.js, src/humanPose/Animation.js, src/humanPose/HumanPoseAnalyzer.js, src/humanPose/draw.js, src/humanPose/index.js, src/motionStudy/motionStudy.js, src/motionStudy/regionCard.js, src/motionStudy/timeline.js, src/utilities/makeTextInput.js
With the latest ios build and the corresponding core-addon PR this should enable the ability to click "Show Spatial Video" while viewing a highlight animation playing to see the corresponding video at that time. Note that there's no handling of the recording device's orientation, suggestions welcome.
=> Analytics: Simultaneous video recording

css/index.css, src/avatar/iconMenu.js, src/device/onLoad.js, src/device/tracking.js, src/gui/ar/areaTargetScanner.js, src/gui/modal.js, src/network/index.js
- updated notification styles and changed notification function name
- maintained old styles in new classes .statusBar-tbr and .statusBarText-tbr to maintain notification functionality where new function showBannerNotification has not been implemented yet
=> UI status notification update

src/motionStudy/motionStudy.js, src/motionStudy/timeline.js
Replace approach of timeline drawing poses from its own list of poses to draw spaghetti lines on timeline
=> Draw spaghetti on timeline

src/avatar/draw.js
Fixes issue where width of pointer dotted lines are very thick on mobile web browser. Also makes the lines slightly thinner on desktop, which matches the visual width of the pointer lines in the AR app a bit more closely.
Before (desktop):
After (desktop):
Before (mobile):
After (mobile):
=> Improve avatar pointer line width

src/ai/index.js, src/network/index.js
Will only work if connected to cloud-proxy, and cloud-proxy has been updated
=> Update AI module to use cloud-proxy-based language service

css/index.css, src/device/onLoad.js
- restored creation of notification container
- reduced width of top screen notification to 50% to avoid conflicts with other UI
=> added creation of notification container and adjusted style

src/motionStudy/motionStudy.js, src/motionStudy/regionCard.js
Fixes an issue where the first load of a motion study after opening a page would feature regionCards without any pose data
=> Motion study better hydration

src/app/index.js, src/motionStudy/index.js
=> Human tracking toggle anonymization

src/humanPose/ErgonomicsData.js, src/humanPose/HumanPoseAnalyzer.js, src/humanPose/MotionStudyColors.js, src/humanPose/MuriLens.js, src/humanPose/MuriScore.js, src/humanPose/OverallRebaLens.js, src/humanPose/RebaLens.js, src/humanPose/ValueAddWasteTimeLens.js, src/humanPose/constants.js, src/humanPose/rebaScore.js, src/motionStudy/motionStudy.js, src/motionStudy/regionCard.js
Contains calculation of Muri score as defined by Volvo.
Adds this ergonomic score to analytic lenses.
Calculates evolved version of statistics included in current Muri Excel sheet used in Volvo. These expand a lot the current CSV export. They can be repurposed for other types of future exports or visualisations within Toolbox. 
Cleaned up few things in REBA score which came up during implementation of Muri score.
=> Human analytics muri score

src/humanPose/ErgonomicsData.js
Twist angles are under or over estimated in some scenarios when the twist is combined with large front and/or side bend of body part.
=> Human analytics twist fix

src/device/index.js, src/gui/scene/Renderer.js, src/gui/threejsScene.js
Requires https://github.com/ptcrealitylab/vuforia-spatial-edge-server/pull/1091
=> Add raycasting against tools

css/index.css, src/avatar/draw.js, src/avatar/index.js
Move dotted lines above 3D content
=> Spatial pointer z index

src/avatar/index.js, src/avatar/network.js, src/avatar/utils.js
Removes references to AI API keys from frontend; all handled on the backend in https://github.com/ptcrealitylab/language-service/pull/1
=> Remove AI API keys from client

css/index.css, src/avatar/iconMenu.js, src/avatar/index.js
Small update: adds a text bubble on the screen if anyone is following you. Clicking on it makes all of your followers stop following you.
=> Button to stop sharing your perspective

src/avatar/network.js
Additional measure to improve performance in sessions with many users; the BatchedUpdateAggregator on the server only helps reduce traffic sent *by* the server, but clients need to also reduce traffic sent *to* the server to prevent it from being overwhelmed.
ChatGPT made this nice plot of different parameters for `getDynamicFPSLimit` – I went with the blue line for now.
=> lower the rate of sending avatar position/cursor/beam updates when many clients are connected

src/motionStudy/ImportStepsButton.js, src/motionStudy/motionStudy.js
Minor break of backwards compatibility with anything recorded using the demo process plan (not expected to have any impact)
=> Support loading plans by name
